let sipa = {
    cultivos: [
        { name: "Yuca", sipa_id: 7, rend: 5.5 },
        { name: "Boniato", sipa_id: 5, rend: 4.3 },
        { name: "Malanga", sipa_id: 6, rend: 8.5 },
        { name: "Plátano Fruta", sipa_id: 13, rend: 25 },
        { name: "Plátano Burro", sipa_id: 12, rend: 8.75 },
        { name: "Plátano Macho", sipa_id: 11, rend: 9 },
        { name: "Ñame", sipa_id: 8, rend: 0 },
        { name: "Papa", sipa_id: 4, rend: 0 },
        { name: "Caldocín", sipa_id: 0, rend: 0 },
        { name: "Fruta del Pan", sipa_id: 0, rend: 0 },
        { name: "Otras Viandas", sipa_id: 0, rend: 0 },
        { name: "Acelga", sipa_id: 0, rend: 0 },
        { name: "Ají Cachucha", sipa_id: 0, rend: 0 },
        { name: "Ají Chay", sipa_id: 0, rend: 0 },
        { name: "Ajo", sipa_id: 18, rend: 0 },
        { name: "Ajo Puerro", sipa_id: 0, rend: 0 },
        { name: "Apio", sipa_id: 0, rend: 0 },
        { name: "Berenjena", sipa_id: 0, rend: 0 },
        { name: "Calabaza", sipa_id: 20, rend: 8 },
        { name: "Cebolla", sipa_id: 17, rend: 0 },
        { name: "Cebolla Multiplicadora", sipa_id: 0, rend: 0 },
        { name: "Cebollino", sipa_id: 0, rend: 0 },
        { name: "Col", sipa_id: 23, rend: 0 },
        { name: "Col China", sipa_id: 0, rend: 0 },
        { name: "Col King", sipa_id: 0, rend: 0 },
        { name: "Culantro", sipa_id: 0, rend: 0 },
        { name: "Espinaca", sipa_id: 0, rend: 0 },
        { name: "Habichuela", sipa_id: 0, rend: 0 },
        { name: "Lechuga", sipa_id: 0, rend: 0 },
        { name: "Moringa", sipa_id: 0, rend: 0 },
        { name: "Oreganito", sipa_id: 0, rend: 0 },
        { name: "Orégano", sipa_id: 0, rend: 0 },
        { name: "Perejil", sipa_id: 0, rend: 0 },
        { name: "Quimbombó", sipa_id: 0, rend: 0 },
        { name: "Rábano", sipa_id: 0, rend: 0 },
        { name: "Remolacha", sipa_id: 0, rend: 0 },
        { name: "Zanahoria", sipa_id: 0, rend: 0 },
        { name: "Melón", sipa_id: 22, rend: 0 },
        { name: "Pepino", sipa_id: 21, rend: 5 },
        { name: "Pimiento", sipa_id: 19, rend: 8 },
        { name: "Tomate", sipa_id: 15, rend: 8 },
        { name: "Otras Hortalizas", sipa_id: 24, rend: 0 },
        { name: "Fruta Bomba", sipa_id: 50, rend: 20 },
        { name: "Guayaba", sipa_id: 49, rend: 0 },
        { name: "Mango", sipa_id: 48, rend: 0 },
        { name: "Piña", sipa_id: 51, rend: 0 },
        { name: "Limón", sipa_id: 43, rend: 0 },
        { name: "Toronja", sipa_id: 42, rend: 0 },
        { name: "Naranja", sipa_id: 41, rend: 0 },
        { name: "Aguacate", sipa_id: 52, rend: 0 },
        { name: "Mamey", sipa_id: 0, rend: 0 },
        { name: "Anón", sipa_id: 0, rend: 0 },
        { name: "Caranbola", sipa_id: 0, rend: 0 },
        { name: "Ciruela", sipa_id: 0, rend: 0 },
        { name: "Anoncillo", sipa_id: 0, rend: 0 },
        { name: "Tamarindo", sipa_id: 0, rend: 0 },
        { name: "Otros Frutales", sipa_id: 53, rend: 0 },
        { name: "Arroz Consumo", sipa_id: 26, rend: 0 },
        { name: "Fríjol Blanco", sipa_id: 0, rend: 0 },
        { name: "Fríjol Colorado", sipa_id: 0, rend: 0 },
        { name: "Fríjol Negro", sipa_id: 0, rend: 0 },
        { name: "Otros Fríjoles", sipa_id: 31, rend: 0 },
        { name: "Maíz seco en grano", sipa_id: 0, rend: 0 },
        { name: "Maíz tierno", sipa_id: 0, rend: 0 },
        { name: "Garbanzo", sipa_id: 33, rend: 0 },
        { name: "Maní", sipa_id: 0, rend: 0 },
        { name: "Otros Granos", sipa_id: 39, rend: 0 },
        { name: "Carne de cerdo", sipa_id: 81, rend: 0 },
        { name: "Carne de conejo", sipa_id: 84, rend: 0 },
        { name: "Carne de ovino", sipa_id: 82, rend: 0 },
        { name: "Carne de caprino", sipa_id: 83, rend: 0 },
        { name: "Peces", sipa_id: 87, rend: 0 },
        { name: "Carnes de aves", sipa_id: 71, rend: 0 },
        { name: "Huevos de aves", sipa_id: 80, rend: 0 },
        { name: "Otras proteínas", sipa_id: 0, rend: 0 },
    ]
};



module.exports = sipa;